---
argocd:
  global:
    domain: argocd.homelab-main.local
  config:
    params:
    # https://github.com/argoproj/argo-cd/issues/2953
      server.insecure: true
  server:
    extraArgs:
      - --insecure
    ingress:
      enabled: true
      ingressClassName: "nginx"
      annotations:
        cert-manager.io/cluster-issuer: "letsencrypt"
