---
argo-cd:
  global:
    domain: argocd.do.theops.dev
  config:
    params:
      # https://github.com/argoproj/argo-cd/issues/2953
      server.insecure: true
  server:
    extraArgs:
      - --insecure

    resources:
      limits:
        cpu: 100m
        memory: 128Mi
      requests:
        cpu: 50m
        memory: 64Mi

    pdb:
      enabled: false
      minAvailable: 1

    metrics:
      enabled: false
      serviceMonitor:
        enabled: false
