repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: Trufflehog Secrets Scan
        always_run: true
        entry: trufflehog filesystem . --fail
        language: system
        pass_filenames: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
default_stages:
  - pre-commit
fail_fast: true
