# .pre-commit-config.yaml
- repo: https://github.com/pre-commit/mirrors-trufflehog
  rev: v3.0.0 # Make sure to use the latest tag or version
  hooks:
    - id: trufflehog
      name: TruffleHog Secret Scanning
      entry: trufflehog --json .
      language: system
      types: [text]
      pass_filenames: true

- repo: https://github.com/pre-commit/mirrors-prettier
  rev: v3.0.0
  hooks:
    - id: prettier
