repos:
  - repo: local
    hooks:
      - id: trufflehog
        name: Trufflehog Secrets Scan
        always_run: true
        entry: trufflehog filesystem . --fail --exclude-paths=.trufflehog_exclude
        language: system
        pass_filenames: true
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.0
    hooks:
      - id: prettier
        args: ["--write"]
        exclude: ^charts/|^argocd/cluster-resources/
  - repo: https://github.com/adrienverge/yamllint
    rev: v1.26.3
    hooks:
      - id: yamllint
        files: ^(charts|ansible|argocd)/.*\.ya?ml$
        exclude: ^(opentofu/.*)
default_stages:
  - pre-commit
fail_fast: true
