---
- name: Get List of Users
  ansible.builtin.shell:
    cmd: |
      getent passwd | grep -i home
    creates: /tmp/kubeconfig_users
  register: users

- name: Create Kube Directory
  ansible.builtin.file:
    name: '{{ item.split(":")[5] }}/.kube'
    state: directory
    owner: '{{ item.split(":")[0] }}'
    group: '{{ item.split(":")[0] }}'
    mode: "0755"
  loop: "{{ users.stdout_lines }}"

- name: Copy Kubeconfig to Users
  ansible.builtin.copy:
    remote_src: true
    src: /etc/rancher/k3s/k3s.yaml
    dest: '{{ item.split(":")[5] }}/.kube/config'
    owner: '{{ item.split(":")[0] }}'
    group: '{{ item.split(":")[0] }}'
    mode: "0644"
  loop: "{{ users.stdout_lines }}"
