traefik:
  service:
    enabled: true
    spec:
      loadBalancerIP: "134.199.185.242"
  podDisruptionBudget:
    enabled: true
    minAvailable: 1
  kubernetesGateway:
    enabled: true
    labelSelector:
      ingressClass: traefik-gateway
  ingressRoute:
    dashboard:
      enabled: true
  logs:
    general:
      level: "INFO"
  metrics:
    prometheus:
      serviceMonitor:
        enabled: true
      service:
        enabled: true
