{{- range $clusterApp, $appConfig := .Values.clusterResources }}
{{- if $appConfig.enabled }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $clusterApp }}
  namespace: argo
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: {{ $appConfig.namespace }}
    server: {{ $.Values.targetCluster.name }}
  project: cluster-resources
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
  source:
    path: "charts/{{ $clusterApp }}"
    repoURL: https://github.com/TheOpsDev/homelab
    targetRevision: {{ $appConfig.branch }}
    helm:
      releaseName: {{ $clusterApp }}
      valueFiles:
        - values.yaml
{{- end }}
{{- end }}