---
- name: Create Ansible User
  hosts: test
  gather_facts: false
  become: true
  tags: bootstrap
  tasks:
    - name: Create Ansible Group
      ansible.builtin.group:
        name: ansible
        gid: 4000
        state: present
    - name: Create Ansible User
      ansible.builtin.user:
        name: ansible
        group: ansible
        shell: /bin/bash
        generate_ssh_key: true
        ssh_key_type: ECDSA
        state: present
    - name: Provide Ansible Sudoer Access
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/ansible
        create: true
        line: "%ansible ALL=(ALL) NOPASSWD: ALL"
        mode: "0640"
        owner: root
        group: root
        state: present
