---
- name: Install and Setup K3s Server
  hosts: prod
  gather_facts: true
  become: true
  tasks:
    - name: Prep K3s Server
      ansible.builtin.include_role:
        name: k3s-prereq
    - name: Configure K3s Server
      ansible.builtin.include_role:
        name: k3s-server
