{{- if .Values.addressPools.enabled -}}
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: {{ .Values.addressPools.name }}
  namespace: metallb-system
spec:
  ipAddressPools:
  - {{ .Values.addressPools.name }}
{{- end -}}